version: '3.8'

services:
  backend:
    build:
      context: ./novaOps-back/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    environment:
      - PYTHONPATH=/app
  frontend:
    build:
        context: ./novaOPS-front/frontend
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend